title: Entreblogs
description: Um espaço para compartilhar perspectivas sobre os mesmos temas, cada um do seu jeitinho e no seu próprio blog.

url: "https://bamoretti.github.io"
baseurl: "/entreblogs"

markdown: kramdown

excerpt_separator: "<!--more-->"

permalink: :slug/
future: false

defaults:
  - scope:
      path: "tags"
      type: pages
    values:
      permalink: /:slug/

exclude:
- README.md
- LICENSE.md
